services:
  - type: web
    name: id-making-app
    runtime: node
    plan: free
    buildCommand: apt-get update && apt-get install -y libreoffice-writer && npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
